# SQLite (portável)
quarkus.datasource.db-kind=other
quarkus.datasource.jdbc.driver=org.sqlite.JDBC
quarkus.datasource.jdbc.url=jdbc:sqlite:./target/simuinvest.db

# Hibernate: schema via Flyway
#quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.schema-management.strategy=none
quarkus.hibernate-orm.dialect=org.hibernate.community.dialect.SQLiteDialect

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

# TEST profile (banco separado)
%test.quarkus.datasource.jdbc.url=jdbc:sqlite:./target/simuinvest-test.db
%test.quarkus.hibernate-orm.dialect=org.hibernate.community.dialect.SQLiteDialect
%test.quarkus.flyway.migrate-at-start=true
%test.quarkus.flyway.locations=db/migration

# Porta randômica nos testes
quarkus.http.test-port=0

# JWT - verificação
mp.jwt.verify.publickey.location=token/publicKey.pem
mp.jwt.verify.issuer=simu-invest-api

# JWT - assinatura (usado só para gerar token no /auth/token)
smallrye.jwt.sign.key.location=token/privateKey.pem

quarkus.smallrye-openapi.security-scheme=jwt
quarkus.smallrye-openapi.security-scheme-name=JWT
quarkus.smallrye-openapi.security-scheme-description=Use "Bearer <token>"
quarkus.smallrye-openapi.security-scheme-type=http
quarkus.smallrye-openapi.security-scheme-bearer-format=JWT